### PR TITLE
Adding an option to keep the profile aliases even when sanitizing.

### LINKED ISSUE #193: profiles deleted after Firefox restart
I set my browser to delete everything when I quit Firefox (cookies, history, etc...). This was never an issue with MultiFox in the past, but now (since 3.1.0 possibly), when I re-start Firefox, all my profiles are deleted.

### PR DESCRIPTION
**Pull request by dorfsmay**
Closes #193

### CODE REVIEW

**Comment by hultmann** [comment]
What about "When restart Firefox, remove all Multifox profiles"? (i.e. ignore other sanitize prefs, shouldSanitize could be removed)

**Comment by dorfsmay** [comment]
In the description?

Or make it a copletely different option that removes/keep profiles regardless of all other options? This would definitely be less confusing.

By the way, I'm using the version built from this PR and love it!

**Comment by hultmann** [comment]
Yes, a different option that would ignore other sanitize prefs.

**Comment by dorfsmay** [comment]
This option clears or keep profies regardless of Firefox sanitize/clear options.

**Comment by dorfsmay** [comment]
@hultmann: Any chance you look at this Pr? Any comment? Thanks.

**Comment by hultmann** [comment]
I'll test it today

**Comment by hultmann** [comment]
Please edit this:

```
-var _prefName = "extensions.multifox@hultmann.clearProfiles";
+var _prefName = "extensions.${EXT_ID}.clearProfiles";
```

Please add the new pref to

```
    if (isInstall) {
      Services.prefs.setBoolPref("services.sync.prefs.sync.extensions.${EXT_ID}.alias", true);
      Services.prefs.setBoolPref("services.sync.prefs.sync.extensions.${EXT_ID}.windowMode", true);
      var desc = util.getTextFrom("extensions.${EXT_ID}.description", "about-multifox");
      util.setUnicodePref("description", desc);
    }
```

(PS. options.xul needs a locale file, I'll do it later)

**Comment by dorfsmay** [comment]
bump?

**Comment by hultmann** [comment]
hmmm it seems Github did not notify me about your new commit. I'll test and merge today or tomorrow!

**Comment by dorfsmay** [comment]
No worries, I know that we're all get busy and that glitch like this happens, hence the bump!

**Pull request merged**
